version: '3.8'

services:
  database:
    container_name: logglizer-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: logglizer
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: logglizer-php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/home/awujoola/Documents/Symfony-Projects/logglizer
    depends_on:
      - database
  nginx:
    container_name: logglizer-nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/home/awujoola/Documents/Symfony-Projects/logglizer
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database